### ISSUE TITLE
TASK: Create Index Page

### ISSUE THREAD

**Issue by vitogalv** [CSE442-Project/CSE-442-Project#25]
**Page Composition**
- Button that takes user to Create New Client Account Page
- Button that takes user to Create New Contractor Account Page
- Title displaying company name or slogan
- Some ad copy and images

**HTML FILE:** https://github.com/CSE442-Project/CSE-442-Project/blob/develop/logic/templates/logic/index.html

**Comment by smbond2** [comment]
Acceptance Tests:
-Button to create new client account takes user to the client account creation page
-Button to create new contractor account takes user to the contractor account creation page
-Login button takes user to login page (not for Sprint 1 since database is not implemented yet)
-Company name and relevant pictures are showing
